name: DevOps / Automation

on:
  schedule:
    - cron: "0 3 25-31 * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: |
      (vars.FLEET_SPOT_CI != 'true' || github.event_name == 'workflow_dispatch') &&
      vars.STALE_ENABLED == 'true'
    permissions: { issues: write, pull-requests: write }
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-stale.yml@ce7169b36bd25b1c4c0c8077aa78ecde6d6ca7d5  # v1.6.0
    with:
      runner: ${{ (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') && '["ubuntu-latest"]' || '["self-hosted","spot","linux","x64"]' }}
